### ISSUE TITLE
chartsDataCollector died, spawning replacement

### ISSUE THREAD

**Issue by xiego** [forknote/forknote-pool#21]
```
TypeError: Cannot read property 'minersHashrate' of undefined
    at /home/****/forknote-pool/lib/charts.js:166:22
    at IncomingMessage.<anonymous> (/home/ubuntu/forknote-pool/lib/apiInterfaces.js:31:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Seems like a noncritical error. This appears to the be code in question.
```
function getUsersHashrates(callback) {
    apiInterfaces.pool('/miners_hashrate', function(error, data) {
        callback(data.minersHashrate);
    });
```

**Comment by dinho-afsn** [comment]
I same problem

**Comment by Driez** [comment]
je suis monte!

**Comment by zhiapp-com** [comment]
i same problem
