### ISSUE TITLE
TypeError: Cannot read property 'pool' of undefined

### ISSUE THREAD

**Issue by zhq1** [forknote/forknote-pool#36]
root@vultr:~/forknote-pool# node init.js
2017-10-28 08:00:21 [master] Pool spawned on 1 thread(s)
2017-10-28 08:00:23 [unlocker] Started
2017-10-28 08:00:23 [payments] Started
2017-10-28 08:00:23 [charts] Started
2017-10-28 08:00:23 [unlocker] No blocks candidates in redis
2017-10-28 08:00:23 [charts] Started
2017-10-28 08:00:23 [chartsDataCollector] Started
2017-10-28 08:00:23 [payments] No workers' balances reached the minimum payment threshold
2017-10-28 08:00:23 [api] API started & listening on port 8117
2017-10-28 08:00:53 [unlocker] No blocks candidates in redis

2017-10-28 08:01:23 [unlocker] No blocks candidates in redis

TypeError: Cannot read property 'pool' of undefined
    at /root/forknote-pool/lib/charts.js:148:30
    at IncomingMessage.<anonymous> (/root/forknote-pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

TypeError: Cannot read property 'pool' of undefined
    at /root/forknote-pool/lib/charts.js:148:30
    at IncomingMessage.<anonymous> (/root/forknote-pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

TypeError: Cannot read property 'pool' of undefined
    at /root/forknote-pool/lib/charts.js:154:30
    at IncomingMessage.<anonymous> (/root/forknote-pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

TypeError: Cannot read property 'pool' of undefined
    at /root/forknote-pool/lib/charts.js:154:30
    at IncomingMessage.<anonymous> (/root/forknote-pool/lib/apiInterfaces.js:31:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

2017-10-28 08:01:23 [master] chartsDataCollector died, spawning replacement...
2017-10-28 08:01:25 [charts] Started
2017-10-28 08:01:25 [chartsDataCollector] Started
^Croot@vultr:~/forknote-pool#

**Comment by cycleworm** [comment]
how does your config file of the pool and website look like?

**Comment by zhiapp-com** [comment]
i am also the same problem,

nodejs problem?

**Comment by yx79** [comment]
i restart the VPS, and the error went away.
I think maybe needing reboot

**Comment by BlueFlo0d** [comment]
Same problem.
node v0.10.48
could anybody figure out what's wrong?
