### ISSUE TITLE
Cryptonote Util Package Error

### ISSUE THREAD

**Issue by MahatmaJapa** [forknote/forknote-pool#52]
> bignum@0.12.5 install /home/elsasha/pool/node_modules/bignum
> node-pre-gyp install --fallback-to-build

[bignum] Success: "/home/elsasha/pool/node_modules/bignum/binding/bignum.node" is installed via remote

> cryptonote-util@0.0.1 install /home/elsasha/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/home/elsasha/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
../src/main.cc: In function ‘v8::Handle<v8::Value> except(const char*)’:
../src/main.cc:21:44: error: ‘New’ is not a member of ‘v8::String’
     return ThrowException(Exception::Error(String::New(msg)));
                                            ^
../src/main.cc:21:61: error: ‘ThrowException’ was not declared in this scope
     return ThrowException(Exception::Error(String::New(msg)));
                                                             ^
../src/main.cc: At global scope:
../src/main.cc:80:34: error: ‘Arguments’ does not name a type
 Handle<Value> convert_blob(const Arguments& args) {
                                  ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> convert_blob(const int&)’:
/usr/include/nodejs/deps/v8/include/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:81:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:83:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:86:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:111:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:111:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:111:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/usr/include/nodejs/src/node_buffer.h:28:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length)
                                        ^
/usr/include/nodejs/src/node_buffer.h:28:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:36:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:36:40: note:   candidate expects 5 arguments, 2 provided
/usr/include/nodejs/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:43:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:112:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:115:34: error: ‘Arguments’ does not name a type
 Handle<Value> get_block_id(const Arguments& args) {
                                  ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> get_block_id(const int&)’:
/usr/include/nodejs/deps/v8/include/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:116:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:118:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:121:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:137:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block
           ^
../src/main.cc:137:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block
             ^
../src/main.cc:137:84: error: no matching function for call to ‘New(char*, long unsigned int)’
 ffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block_id));
                                                                              ^
In file included from ../src/main.cc:3:0:
/usr/include/nodejs/src/node_buffer.h:28:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length)
                                        ^
/usr/include/nodejs/src/node_buffer.h:28:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:36:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:36:40: note:   candidate expects 5 arguments, 2 provided
/usr/include/nodejs/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:43:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:138:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:141:42: error: ‘Arguments’ does not name a type
 Handle<Value> construct_block_blob(const Arguments& args) {
                                          ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> construct_block_blob(const int&)’:
/usr/include/nodejs/deps/v8/include/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:142:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:144:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 2)
              ^
../src/main.cc:147:46: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> block_template_buf = args[0]->ToObject();
                                              ^
../src/main.cc:148:37: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> nonce_buf = args[1]->ToObject();
                                     ^
../src/main.cc:179:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:179:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:179:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/usr/include/nodejs/src/node_buffer.h:28:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length)
                                        ^
/usr/include/nodejs/src/node_buffer.h:28:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:36:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:36:40: note:   candidate expects 5 arguments, 2 provided
/usr/include/nodejs/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:43:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:180:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:183:37: error: ‘Arguments’ does not name a type
 Handle<Value> convert_blob_bb(const Arguments& args) {
                                     ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> convert_blob_bb(const int&)’:
/usr/include/nodejs/deps/v8/include/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:184:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:186:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:189:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:204:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:204:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:204:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/usr/include/nodejs/src/node_buffer.h:28:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length)
                                        ^
/usr/include/nodejs/src/node_buffer.h:28:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:31:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/usr/include/nodejs/src/node_buffer.h:36:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:36:40: note:   candidate expects 5 arguments, 2 provided
/usr/include/nodejs/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:43:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:205:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:208:36: error: ‘Arguments’ does not name a type
 Handle<Value> address_decode(const Arguments& args) {
                                    ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> address_decode(const int&)’:
/usr/include/nodejs/deps/v8/include/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:209:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:211:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:214:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:224:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:224:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:315:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:228:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:228:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:315:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:231:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:231:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:315:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:233:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Integer::New(static_cast<uint32_t>(prefix)));
                  ^
../src/main.cc:233:66: error: no matching function for call to ‘v8::Integer::New(uint32_t)’
     return scope.Close(Integer::New(static_cast<uint32_t>(prefix)));
                                                                  ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:2499:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/usr/include/nodejs/deps/v8/include/v8.h:2499:25: note:   candidate expects 2 arguments, 1 provided
../src/main.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/main.cc:237:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("construct_block_blob"), FunctionTemplate::N
                  ^
../src/main.cc:237:103: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
 ("construct_block_blob"), FunctionTemplate::New(construct_block_blob)->GetFunct
                                                                     ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:238:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("get_block_id"), FunctionTemplate::New(get_b
                  ^
../src/main.cc:238:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
 tring::NewSymbol("get_block_id"), FunctionTemplate::New(get_block_id)->GetFunct
                                                                     ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:239:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("convert_blob"), FunctionTemplate::New(conve
                  ^
../src/main.cc:239:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
 tring::NewSymbol("convert_blob"), FunctionTemplate::New(convert_blob)->GetFunct
                                                                     ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:240:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("convert_blob_bb"), FunctionTemplate::New(co
                  ^
../src/main.cc:240:93: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
 :NewSymbol("convert_blob_bb"), FunctionTemplate::New(convert_blob_bb)->GetFunct
                                                                     ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:241:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("address_decode"), FunctionTemplate::New(add
                  ^
../src/main.cc:241:91: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
 g::NewSymbol("address_decode"), FunctionTemplate::New(address_decode)->GetFunct
                                                                     ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/main.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/usr/include/nodejs/deps/v8/include/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
cryptonote.target.mk:102: recipe for target 'Release/obj.target/cryptonote/src/main.o' failed
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/elsasha/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-42-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/elsasha/pool/node_modules/cryptonote-util
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
cryptonote-universal-pool@0.0.1 /home/elsasha/pool
├── async@2.6.0 
├── base58-native@0.1.4 
├── bignum@0.12.5 
├── cli-color@1.2.0 
├── dateformat@3.0.2 
├── multi-hashing@0.0.9  (git://github.com/fancoder/node-multi-hashing.git#ec00b7429b668b3366d80a8fa85e9c22b4792d70)
└── redis@2.8.0 

npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/elsasha/pool/npm-debug.log

**Comment by nskuijpers** [comment]
I got the same error

**Comment by PCPisChill** [comment]
Same problem, Debian 9 Stretch, I've tried 0.10.0, 0.10.28, 0.10.29, 0.10.48, 0.12.18, 9.4.0 with same issue.

**Comment by nskuijpers** [comment]
The cryptonote pool I have running with node version v0.47, but this project the cryptonote util not complile.

**Comment by fmarines** [comment]
Same issue here  Centos 7( 3.10.0-693.17.1.el7.x86_64) , node 8.9.4 npm 5.6.0

**Comment by pbt39ppc** [comment]
ubuntu 18.04 lts too
