### ISSUE TITLE
compile error at cryptonote-util

### ISSUE THREAD

**Issue by khunpoum** [forknote/forknote-pool#65]
```
npm update

> cryptonote-util@0.0.1 install /root/trtl/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/root/trtl/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
../src/main.cc: In function ‘v8::Handle<v8::Value> except(const char*)’:
../src/main.cc:21:44: error: ‘New’ is not a member of ‘v8::String’
     return ThrowException(Exception::Error(String::New(msg)));
                                            ^
../src/main.cc:21:61: error: ‘ThrowException’ was not declared in this scope
     return ThrowException(Exception::Error(String::New(msg)));
                                                             ^
../src/main.cc: At global scope:
../src/main.cc:80:34: error: ‘Arguments’ does not name a type
 Handle<Value> convert_blob(const Arguments& args) {
                                  ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> convert_blob(const int&)’:
/root/.node-gyp/8.9.4/include/node/v8.h:874:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:81:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:83:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:86:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:111:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:111:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:111:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:112:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:115:34: error: ‘Arguments’ does not name a type
 Handle<Value> get_block_id(const Arguments& args) {
                                  ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> get_block_id(const int&)’:
/root/.node-gyp/8.9.4/include/node/v8.h:874:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:116:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:118:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:121:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:137:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block_id));
           ^
../src/main.cc:137:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block_id));
             ^
../src/main.cc:137:84: error: no matching function for call to ‘New(char*, long unsigned int)’
     Buffer* buff = Buffer::New(reinterpret_cast<char*>(&block_id), sizeof(block_id));
                                                                                    ^
In file included from ../src/main.cc:3:0:
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:138:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:141:42: error: ‘Arguments’ does not name a type
 Handle<Value> construct_block_blob(const Arguments& args) {
                                          ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> construct_block_blob(const int&)’:
/root/.node-gyp/8.9.4/include/node/v8.h:874:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:142:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:144:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 2)
              ^
../src/main.cc:147:46: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> block_template_buf = args[0]->ToObject();
                                              ^
../src/main.cc:148:37: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> nonce_buf = args[1]->ToObject();
                                     ^
../src/main.cc:188:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:188:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:188:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:189:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:192:37: error: ‘Arguments’ does not name a type
 Handle<Value> convert_blob_bb(const Arguments& args) {
                                     ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> convert_blob_bb(const int&)’:
/root/.node-gyp/8.9.4/include/node/v8.h:874:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:193:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:195:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:198:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:213:11: error: expected primary-expression before ‘*’ token
     Buffer* buff = Buffer::New(output.data(), output.size());
           ^
../src/main.cc:213:13: error: ‘buff’ was not declared in this scope
     Buffer* buff = Buffer::New(output.data(), output.size());
             ^
../src/main.cc:213:60: error: no matching function for call to ‘New(const char*, std::__cxx11::basic_string<char>::size_type)’
     Buffer* buff = Buffer::New(output.data(), output.size());
                                                            ^
In file included from ../src/main.cc:3:0:
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:52:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:55:40: note:   no known conversion for argument 1 from ‘const char*’ to ‘v8::Isolate*’
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:60:40: note:   candidate expects 5 arguments, 2 provided
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note:   candidate expects 3 arguments, 2 provided
../src/main.cc:214:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(buff->handle_);
                  ^
../src/main.cc: At global scope:
../src/main.cc:217:36: error: ‘Arguments’ does not name a type
 Handle<Value> address_decode(const Arguments& args) {
                                    ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> address_decode(const int&)’:
/root/.node-gyp/8.9.4/include/node/v8.h:874:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/main.cc:218:17: error: within this context
     HandleScope scope;
                 ^
../src/main.cc:220:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1)
              ^
../src/main.cc:223:34: error: invalid types ‘const int[int]’ for array subscript
     Local<Object> target = args[0]->ToObject();
                                  ^
../src/main.cc:233:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:233:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:312:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:237:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:237:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:312:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:240:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/main.cc:240:38: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:312:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/main.cc:242:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Integer::New(static_cast<uint32_t>(prefix)));
                  ^
../src/main.cc:242:66: error: no matching function for call to ‘v8::Integer::New(uint32_t)’
     return scope.Close(Integer::New(static_cast<uint32_t>(prefix)));
                                                                  ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:2914:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/root/.node-gyp/8.9.4/include/node/v8.h:2914:25: note:   candidate expects 2 arguments, 1 provided
../src/main.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/main.cc:246:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("construct_block_blob"), FunctionTemplate::New(construct_block_blob)->GetFunction());
                  ^
../src/main.cc:246:103: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("construct_block_blob"), FunctionTemplate::New(construct_block_blob)->GetFunction());
                                                                                                       ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:247:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("get_block_id"), FunctionTemplate::New(get_block_id)->GetFunction());
                  ^
../src/main.cc:247:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("get_block_id"), FunctionTemplate::New(get_block_id)->GetFunction());
                                                                                       ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:248:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("convert_blob"), FunctionTemplate::New(convert_blob)->GetFunction());
                  ^
../src/main.cc:248:87: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("convert_blob"), FunctionTemplate::New(convert_blob)->GetFunction());
                                                                                       ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:249:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("convert_blob_bb"), FunctionTemplate::New(convert_blob_bb)->GetFunction());
                  ^
../src/main.cc:249:93: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("convert_blob_bb"), FunctionTemplate::New(convert_blob_bb)->GetFunction());
                                                                                             ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/main.cc:250:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("address_decode"), FunctionTemplate::New(address_decode)->GetFunction());
                  ^
../src/main.cc:250:91: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     exports->Set(String::NewSymbol("address_decode"), FunctionTemplate::New(address_decode)->GetFunction());
                                                                                           ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/main.cc:2:
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/root/.node-gyp/8.9.4/include/node/v8.h:5395:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
cryptonote.target.mk:107: recipe for target 'Release/obj.target/cryptonote/src/main.o' failed
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/root/trtl/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-87-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/trtl/pool/node_modules/cryptonote-util
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-05T19_09_09_742Z-debug.log
```

**Comment by lanaiscool** [comment]
same error here

**Comment by jogc** [comment]
same.

this is on debian stretch + nodejs 8.9.4-1nodesource1

**Comment by calidion** [comment]
try node 0.10.x

**Comment by ghost** [comment]
This fixed it for me
sudo apt-get install libboost-all-dev

Then again run npm update

**Comment by ghost** [comment]
Try with this:

Version 0.10.^ of Node.js is most suitable with the actual development stage. That said, since Ubuntu 16 come with version 4.^ of Node.js you will need to downgrade it (just to run the pool).

# install n to manage node version to use
sudo npm install -g n
# use node's version 0.10.^
sudo n 0.10
# you can change after to lastest node's LTS by running `sudo n lts`
# learn more with `n --help`
